### ISSUE TITLE
training the model by my own dataset  

### ISSUE THREAD

**Issue by gwp2021** [aupendu/zero-restore#4]
Thank you for your sharing, I am very interested in your sharing. But I only see the test code, I would appreciate it if you could share the source code so I can train my own data .

**Comment by aupendu** [comment]
This is a zero-shot restoration algorithm. Training is done during testing. Please read the paper for more clarification. Run the test code to test the images.

**Comment by gwp2021** [comment]
Thank you very much for your reply, and your method is really innovative




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aupendu ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 晚上11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aupendu/zero-restore] training the model by my own dataset   (Issue #4)





 
This is a zero-shot restoration algorithm. Training is done during testing. Please read the paper for more clarification. Run the test code to test the images.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
