### ISSUE TITLE
Where is the Supplementary material?

### ISSUE THREAD

**Issue by marc-micatka** [aupendu/zero-restore#5]
nice work! Your paper lists multiple references to "Supplementary" but it's not in the attached paper. Do you have a link?

**Comment by aupendu** [comment]
https://openaccess.thecvf.com/content/CVPR2021/supplemental/Kar_Zero-Shot_Single_Image_CVPR_2021_supplemental.pdf

**Comment by marc-micatka** [comment]
Thanks!
