### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Yiting1009** [aupendu/zero-restore#7]
Hi, thanks for your great work!
But I get some problems when I am running watermodel.py. This confuses me for a long time. 
I used the operation: nn.ReLU(inplace=True) -> nn.ReLU(inplace=False), but I still got this error. I don't know how to solve it.
<img width="1028" alt="截屏2022-12-12 12 19 05" src="https://user-images.githubusercontent.com/67905589/206959791-fd217a78-8d86-46d7-bef7-29d34d59c049.png">
Thanks a lot!

**Comment by aupendu** [comment]
nn.ReLU(inplace=True) -> nn.ReLU(inplace=False)

**Comment by wengzp1** [comment]
> 您好，感谢您的出色工作！ 但是当我运行 watermodel.py 时遇到一些问题。这让我困惑了很长时间。 我使用了操作： nn.ReLU(inplace=True) -> nn.ReLU(inplace=False)，但我仍然收到此错误。我不知道如何解决。 多谢！ <img alt="截屏2022-12-12 12 19 05" width="1028" src="https://user-images.githubusercontent.com/67905589/206959791-fd217a78-8d86-46d7-bef7-29d34d59c049.png">

hello,I want to ask did you finally solve the problem？

**Comment by aupendu** [comment]
Add .clone() in SKCov Layer's forward pass

![image](https://github.com/aupendu/zero-restore/assets/23521684/063df879-b001-4374-b9c2-63af6c8acc2f)

**Comment by qwertyuiasdbvezdr** [comment]
> > 您好，感谢您的出色工作！ 但是当我运行 watermodel.py 时遇到一些问题。这让我困惑了很长时间。我使用了操作： nn.ReLU（inplace=True） -> nn。ReLU（inplace=False），但我仍然收到此错误。我不知道如何解决。多谢！<img alt="截屏2022-12-12 12 19 05" width="1028" src="https://user-images.githubusercontent.com/67905589/206959791-fd217a78-8d86-46d7-bef7-29d34d59c049.png">
> 
> 你好，我想问一下你终于解决了问题吗？
