### ISSUE TITLE
The denosing procedure is not found in the provided enhancement code

### ISSUE THREAD

**Issue by LPengYang** [aupendu/zero-restore#9]
Thank you for your wonderful work. In the paper, it is stated that denoising procedure (BM3D) is required in final step for zero-shot image enhancement task, however, the corresponding code is not found in the provided LowLightZeroShot.py. If the denoising code is supposed to add to reproduce the enhanced results presented in the paper.

**Comment by aupendu** [comment]
We use BM3D denoising as a post-processing step to remove the noise. The Matlab code can be found here: https://webpages.tuni.fi/foi/GCF-BM3D/index.html
